name: web3_wallet
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.16.1 <3.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  url_launcher: ^6.0.20
  walletconnect_dart: ^0.0.8
  dart_web3: ^0.0.3
dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
flutter:
  uses-material-design: true
